cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - public

build-image:
  image: docker:stable
  services:
    - docker.dind
  stage: prepare
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd .meta
    - docker build -t $CI_REGISTRY/knowles-group/gmb:latest .
    - docker push $CI_REGISTRY/knowles-group/gmb:latest
  only:
#    refs:
#      - master
    changes:
      - Dockerfile
build:
  image: registry.gitlab.com/knowles-group/secondquantization
#  only:
#    refs:
#      - master
  tags:
    - group-cluster
  script:
    - procs=$(lscpu -p | egrep -v '^#' | wc -l || echo 1); echo $procs processors available
    - TOP=$PWD
    - git checkout $CI_COMMIT_SHA # because of cache
    - git reset --hard
    - git clean -f src test dependencies
    - cd $TOP; BUILD=build; mkdir -p $BUILD && cd $BUILD && pwd && CC=mpicc CXX=mpicxx cmake -DMPIOPTIONS="--allow-run-as-root" $TOP ; cmake --build . -- -j ${procs} ; cd test;  ctest -V -j ${procs}
